version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 2s
      retries: 30

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    deploy:
      mode: replicated
      replicas: 3
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 -w 1 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
      - env/api.env
    depends_on:
      order-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  stock-service:
    build: ./stock
    image: stock:latest
    deploy:
      mode: replicated
      replicas: 3
    command: gunicorn -b 0.0.0.0:5000 -w 1 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
      - env/api.env
    depends_on:
      stock-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: user:latest
    deploy:
      mode: replicated
      replicas: 3
    command: gunicorn -b 0.0.0.0:5000 -w 1 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
      - env/api.env
    depends_on:
      payment-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    deploy:
      replicas: 4
    command: -f /mnt/locust/locustfile.py --worker --master-host master