services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - general_network
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 2s
      retries: 30

  gateway:
    image: envoyproxy/envoy:v1.33.0
    ports:
      - "8000:80"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - order-service
      - stock-service
      - payment-service
    networks:
      - general_network

  order-service:
    build: ./order
    image: order:latest
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - GATEWAY_URL=http://gateway:80
    networks:
      - redis_network
      - general_network
    command: gunicorn -b 0.0.0.0:5000 -w 1 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
      - env/api.env
    depends_on:
      order-db-master:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  order-db-master:
    image: redis:7.2
    container_name: order-db-master
    hostname: order-db-master
    ports:
      - 6379:6379
    networks:
      - redis_network
    command: redis-server --requirepass redis --maxmemory 512mb --masterauth redis --replica-announce-ip order-db-master

  order-db-replica-1:
    image: redis:7.2
    container_name: order-db-replica-1
    hostname: order-db-replica-1
    ports:
      - 6381:6381
    networks:
      - redis_network
    command: redis-server --requirepass redis --replicaof order-db-master 6379 --masterauth redis --replica-announce-ip order-db-replica-1
    depends_on:
      - order-db-master

  order-db-replica-2:
    image: redis:7.2
    container_name: order-db-replica-2
    hostname: order-db-replica-2
    ports:
      - 6382:6382
    networks:
      - redis_network
    command: redis-server --requirepass redis --replicaof order-db-master 6379 --masterauth redis --replica-announce-ip order-db-replica-2
    depends_on:
      - order-db-master

  order-sentinel-1:
    image: redis:7.2
    container_name: order-sentinel-1
    hostname: order-sentinel-1
    ports:
      - 26479:26479
    networks:
      - redis_network
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel-order-1.conf:/etc/redis/sentinel.conf
    depends_on:
      - order-db-master
      - order-db-replica-1
      - order-db-replica-2

  order-sentinel-2:
    image: redis:7.2
    container_name: order-sentinel-2
    hostname: order-sentinel-2
    ports:
      - 26480:26479
    networks:
      - redis_network
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel-order-2.conf:/etc/redis/sentinel.conf
    depends_on:
      - order-db-master
      - order-db-replica-1
      - order-db-replica-2

  order-sentinel-3:
    image: redis:7.2
    container_name: order-sentinel-3
    hostname: order-sentinel-3
    ports:
      - 26481:26479
    networks:
      - redis_network
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel-order-3.conf:/etc/redis/sentinel.conf
    depends_on:
      - order-db-master
      - order-db-replica-1
      - order-db-replica-2


  stock-service:
    build: ./stock
    image: stock:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - general_network
    command: gunicorn -b 0.0.0.0:5000 -w 1 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
      - env/api.env
    depends_on:
      stock-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  stock-db:
    image: redis:7.2
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - general_network

  payment-service:
    build: ./payment
    image: user:latest
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - general_network
    command: gunicorn -b 0.0.0.0:5000 -w 1 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
      - env/api.env
    depends_on:
      payment-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  payment-db:
    image: redis:7.2
    command: redis-server --requirepass redis --maxmemory 512mb
    networks:
      - general_network

  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    deploy:
      replicas: 4
    command: -f /mnt/locust/locustfile.py --worker --master-host master

networks:
  general_network:
    driver: bridge
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24