name: Pylint Check

on:
  pull_request:
    branches:
      - main  # Adjust as needed

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Adjust as needed

      - name: Install dependencies
        run: |
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Pylint
        run: pylint $(git ls-files '*.py')
